//
// Created by pavel on 27.04.20.
//

#ifndef PA2_2_SEMESTRALKA_EGAMESTATE_H
#define PA2_2_SEMESTRALKA_EGAMESTATE_H


/// Enumeration of all possible game states
enum EGameState {
    GAMESTATE_HUNT_ON_PLAYER, GAMESTATE_NEUTRAL, GAMESTATE_HUNT_ON_GHOSTS, GAMESTATE_VICTORY, GAMESTATE_LOST, GAMESTATE_LOST_LIFE
};

#endif //PA2_2_SEMESTRALKA_EGAMESTATE_H